### ISSUE TITLE
"cannot switch terminal to raw mode" error on Windows

### ISSUE THREAD

**Issue by dluciv** [wavexx/Polyglot.jl#3]
When running native Python interpreters under Windows, following error happens:

    ERROR: Polyglot.BondException("cannot switch terminal to raw mode")

Not sure it is easy to fix, because its primary reason is not Julia or Polyglot, but Windows console itself.

It is possible to work it around, though, by using Cygwin executables as follows:

    py3 = Polyglot.bond!("Python", `c:/cygwin/bin/python3.6m.exe`)

For native Windows distributions of CPython, the probable reason is lack of `termios` module: https://github.com/paradoxxxzero/butterfly/issues/35

But working it around looks very cumbersone, not sure it's a good way for Polyglot: https://stackoverflow.com/a/2409034/539470

**Comment by wavexx** [comment]
This is an issue in the underlying `Expect.jl` module. Support for Windows is something that was added later. It should work if you pin Expect.jl directly from git.

**Comment by wavexx** [comment]
Ah, no, indeed, this is actually generated by the python driver indeed. Mmmh...
