### ISSUE TITLE
Can't get prompt from node.JS under Windows

### ISSUE THREAD

**Issue by dluciv** [wavexx/Polyglot.jl#4]
When trying to `bond!` to Node.JS, under Windows, we get following:

```
julia> n = Polyglot.bond!("JavaScript")
ERROR: Polyglot.BondException("cannot get an interactive prompt using: node")
Stacktrace:
 [1] #bond!#9(::String, ::Base.EnvHash, ::Bool, ::Void, ::Int64, ::String, ::Function, ::String, ::Void, ::Array{String,1}) at C:\Users\d\.julia\v0.6\Polyglot\src\Polyglot.jl:255
 [2] bond!(::String) at C:\Users\d\.julia\v0.6\Polyglot\src\Polyglot.jl:211
```

Under Linux everything works very well

**Comment by wavexx** [comment]
On Wed, Sep 20 2017, Dmitry V. Luciv wrote:
> ```
> julia> n = Polyglot.bond!("JavaScript")
> ERROR: Polyglot.BondException("cannot get an interactive prompt using: node")
> Stacktrace:
>  [1] #bond!#9(::String, ::Base.EnvHash, ::Bool, ::Void, ::Int64, ::String, ::Function, ::String, ::Void, ::Array{String,1}) at C:\Users\d\.julia\v0.6\Polyglot\src\Polyglot.jl:255
>  [2] bond!(::String) at C:\Users\d\.julia\v0.6\Polyglot\src\Polyglot.jl:211
> ```
>
> Under Linux everything works very well

I have to say, it's 10+ years that I do not use windows.

I generally borrow a laptop on windows to do some basic testing, but
it's a platform I would need help with.

**Comment by dluciv** [comment]
Okay, didn't know it's a pain.

Right now I have a few time, but I hope once I can debug it myself and get how to fix it.

**Comment by wavexx** [comment]
On Wed, Sep 20 2017, Dmitry V. Luciv wrote:
> Okay, didn't know it's a pain.

It's not really a pain, it's just that I don't use it at all, so I have
no clue on how the windows console and process I/O works on WIN32.

But it shouldn't be a big issue, technically. As long as the underlying
transport is binary-safe, the rest will work.
